"""add share_links table

Revision ID: 4521175ac87e
Revises: daa789ea5e5d
Create Date: 2026-06-26 19:25:07.570091
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4521175ac87e'
down_revision: str | None = 'daa789ea5e5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pnl_color_scheme', sa.String(length=16), nullable=True),
    sa.Column('trade_grouping', sa.String(length=8), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_share_links_series_id'), 'share_links', ['series_id'], unique=False)
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=True)
    op.create_index(op.f('ix_share_links_user_id'), 'share_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_links_user_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_series_id'), table_name='share_links')
    op.drop_table('share_links')
    # ### end Alembic commands ###
