"""add strategy name columns to fund_movements

Revision ID: 4dd420efaa1d
Revises: 4521175ac87e
Create Date: 2026-06-26 23:32:28.948302
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd420efaa1d'
down_revision: str | None = '4521175ac87e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_movements', sa.Column('from_strategy_name', sa.String(length=128), nullable=True))
    op.add_column('fund_movements', sa.Column('to_strategy_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_movements', 'to_strategy_name')
    op.drop_column('fund_movements', 'from_strategy_name')
    # ### end Alembic commands ###
