"""add voided_at to series

Revision ID: daa789ea5e5d
Revises: 3138927b0e96
Create Date: 2026-06-26 18:11:57.822249
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daa789ea5e5d'
down_revision: str | None = '3138927b0e96'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    op.drop_index(op.f('ix_share_links_series_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_slug'), table_name='share_links', postgresql_where='((slug IS NOT NULL) AND (revoked_at IS NULL))')
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.drop_index(op.f('ix_benchmark_returns_series_id'), table_name='benchmark_returns')
    op.create_index('ix_benchmark_lookup', 'benchmark_returns', ['series_id', 'name', 'ts'], unique=False)
    op.create_index(op.f('ix_fills_ts'), 'fills', ['ts'], unique=False)
    op.create_index(op.f('ix_fills_voided_at'), 'fills', ['voided_at'], unique=False)
    op.drop_constraint(op.f('fills_strategy_id_fkey'), 'fills', type_='foreignkey')
    op.create_foreign_key(None, 'fills', 'strategies', ['strategy_id'], ['id'])
    op.create_index(op.f('ix_fund_movements_voided_at'), 'fund_movements', ['voided_at'], unique=False)
    op.drop_index(op.f('ix_fx_rates_lookup'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_series_id'), table_name='fx_rates')
    op.create_index('ix_fxrate_lookup', 'fx_rates', ['series_id', 'ccy_from', 'ccy_to', 'ts'], unique=False)
    op.drop_constraint(op.f('ingestion_batches_api_key_id_fkey'), 'ingestion_batches', type_='foreignkey')
    op.create_foreign_key(None, 'ingestion_batches', 'api_keys', ['api_key_id'], ['id'])
    op.add_column('series', sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('series', 'validation_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Per-series validation thresholds (max_leverage_ratio, max_drawdown_ratio, require_capital)',
               existing_nullable=True)
    op.create_index(op.f('ix_series_voided_at'), 'series', ['voided_at'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_series_voided_at'), table_name='series')
    op.alter_column('series', 'validation_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Per-series validation thresholds (max_leverage_ratio, max_drawdown_ratio, require_capital)',
               existing_nullable=True)
    op.drop_column('series', 'voided_at')
    op.drop_constraint(None, 'ingestion_batches', type_='foreignkey')
    op.create_foreign_key(op.f('ingestion_batches_api_key_id_fkey'), 'ingestion_batches', 'api_keys', ['api_key_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_fxrate_lookup', table_name='fx_rates')
    op.create_index(op.f('ix_fx_rates_series_id'), 'fx_rates', ['series_id'], unique=False)
    op.create_index(op.f('ix_fx_rates_lookup'), 'fx_rates', ['series_id', 'ccy_from', 'ccy_to', 'ts'], unique=False)
    op.drop_index(op.f('ix_fund_movements_voided_at'), table_name='fund_movements')
    op.drop_constraint(None, 'fills', type_='foreignkey')
    op.create_foreign_key(op.f('fills_strategy_id_fkey'), 'fills', 'strategies', ['strategy_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_fills_voided_at'), table_name='fills')
    op.drop_index(op.f('ix_fills_ts'), table_name='fills')
    op.drop_index('ix_benchmark_lookup', table_name='benchmark_returns')
    op.create_index(op.f('ix_benchmark_returns_series_id'), 'benchmark_returns', ['series_id'], unique=False)
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'], postgresql_nulls_not_distinct=False)
    op.create_table('share_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_accessed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('pnl_color_scheme', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('trade_grouping', sa.VARCHAR(length=8), server_default=sa.text("'day'::character varying"), autoincrement=False, nullable=True),
    sa.Column('lang', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('date_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('share_links_series_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('share_links_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('share_links_pkey')),
    sa.UniqueConstraint('token', name=op.f('share_links_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=False)
    op.create_index(op.f('ix_share_links_slug'), 'share_links', ['slug'], unique=True, postgresql_where='((slug IS NOT NULL) AND (revoked_at IS NULL))')
    op.create_index(op.f('ix_share_links_series_id'), 'share_links', ['series_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('accounts_series_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey')),
    sa.UniqueConstraint('series_id', name=op.f('accounts_series_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
